image: 172.17.0.1:4567/root/pipeline-commander/build-env/alpine:latest

variables:
  GIT_SSL_NO_VERIFY: 1
  #CI_DEBUG_TRACE: "true"

stages:
  - build
  - test
  - integrate

build_job:
  stage: build
  script:
    - cp pipeline-commander.py pipeline-commander
    - chmod +x pipeline-commander
  artifacts:
    paths:
      - pipeline-commander

test_job:
  stage: test
  dependencies:
    - build_job
  variables:
    PRIVATE_TOKEN: this is not a valid token
  script:
    - cp pipeline-commander /usr/bin
    - chmod +x /usr/bin/pipeline-commander
    - echo "need to write some tests"

integrate_job:
  stage: integrate
  dependencies:
    - build_job
  variables:
    PRIVATE_TOKEN: this is not a valid token
  script:
    - cp pipeline-commander /usr/bin
    - chmod +x /usr/bin/pipeline-commander
    - echo running 'never-say-die' branch build which should always return success
    - pipeline-commander -p '${PRIVATE_TOKEN}' -u https://172.17.0.1 pipelines create -r cfriedt/never-say-die -v CI_JOB_TOKEN=${CI_JOB_TOKEN} -i ${CI_PROJECT_ID}; test $? -eq 0
    - echo running 'failing-forward' branch build which should always return failure
    - pipeline-commander -p '${PRIVATE_TOKEN}' -u https://172.17.0.1 pipelines create -r cfriedt/failing-forward -v CI_JOB_TOKEN=${CI_JOB_TOKEN} -i ${CI_PROJECT_ID}; test $? -ne 0
